name: Coveralls

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repo
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Use Node.js 22.x # Nota: 22 es la versión LTS actual más estable
        uses: actions/setup-node@v4 
        with:
          node-version: 22.x

      - name: Installing dependencies
        run: npm ci

      - name: Generating coverage information
        run: npm run coverage # Asegúrate de que este script genere lcov

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Forzamos la ruta al archivo generado por Vitest
          file: ./coverage/lcov.info